// Data from the RNS Discord strats-and-steel channel

// COLUMNS
// 0 (A): Seed
// 1 (B): Area 1
// 2 (C): Area 2
// 3 (D): Area 3
// 4 (E): Area 4
// 5 (F): Area 5
// 6-10 (G-K): Chest 1
// 11-15 (L-P): Chest 2
// 16-20 (Q-U): Chest 3
// 21-25 (V-Z): Chest 4
// 26-30 (AA-AE): Chest 5
// 31-35 (AF-AJ): Chest 6
// 36-38 (AK-AM): Shop 1 Potions
// 39-41 (AN-AP): Shop 1 Potion Prices
// 42-43 (AQ-AR): Shop 1 Primary, Price
// 44-45 (AS-AT): Shop 1 Secondary, Price
// 46-47 (AU-AV): Shop 1 Special, Price
// 48-49 (AW-AX): Shop 1 Defensive, Price
// 50-52 (AY-BA): Shop 2 Potions
// 53-55 (BB-BD): Shop 2 Potion Prices
// 56-57 (BE-BF): Shop 2 Primary, Price
// 58-59 (BG-BH): Shop 2 Secondary, Price
// 60-61 (BI-BJ): Shop 2 Special, Price
// 62-63 (BK-BL): Shop 2 Defensive, Price
// 64-66 (BM-BO): Shop 3 Potions
// 67-69 (BP-BR): Shop 3 Potion Prices
// 70-71 (BS-BT): Shop 3 Primary, Price
// 72-73 (BU-BV): Shop 3 Secondary, Price
// 74-75 (BW-BX): Shop 3 Special, Price
// 76-77 (BY-BZ): Shop 3 Defensive, Price
// 78-80 (CA-CC): Shop 4 Potions
// 81-83 (CD-CF): Shop 4 Potion Prices
// 84-85 (CG-CH): Shop 4 Primary, Price
// 86-87 (CI-CJ): Shop 4 Secondary, Price
// 88-89 (CK-CL): Shop 4 Special, Price
// 90-91 (CM-CN): Shop 4 Defensive, Price

const itemObj = {
  // 0: 'nothing_item',
  // 1: '???',
  // 2: '???',
  // 3: '???',
  // 4: '???',
  // 5: '???',
  // 6: 'Dimi Moonburst',
  // 7: 'Diamond Dimi Moonburst',
  // 8: 'Opal Dimi Moonburst',
  // 9: 'Sapphire Dimi Moonburst',
  // 10: 'Ruby Dimi Moonburst',
  // 11: 'Garnet Dimi Moonburst',
  // 12: 'Emerald Dimi Moonburst',
  // 13: 'Lat Moonburst',
  // 14: 'Diamond Lat Moonburst',
  // 15: 'Opal Lat Moonburst',
  // 16: 'Sapphire Lat Moonburst',
  // 17: 'Ruby Lat Moonburst',
  // 18: 'Garnet Lat Moonburst',
  // 19: 'Emerald Lat Moonburst',
  // 20: 'Astral Swirl',
  // 21: 'Diamond Astral Swirl',
  // 22: 'Opal Astral Swirl',
  // 23: 'Sapphire Astral Swirl',
  // 24: 'Ruby Astral Swirl',
  // 25: 'Garnet Astral Swirl',
  // 26: 'Emerald Astral Swirl',
  // 27: 'Astral Seal',
  // 28: 'Diamond Astral Seal',
  // 29: 'Opal Astral Seal',
  // 30: 'Sapphire Astral Seal',
  // 31: 'Ruby Astral Seal',
  // 32: 'Garnet Astral Seal',
  // 33: 'Emerald Astral Seal',
  // 34: 'Swift Cut',
  // 35: 'Diamond Swift Cut',
  // 36: 'Opal Swift Cut',
  // 37: 'Sapphire Swift Cut',
  // 38: 'Ruby Swift Cut',
  // 39: 'Garnet Swift Cut',
  // 40: 'Emerald Swift Cut',
  // 41: 'Knife Juggle',
  // 42: 'Diamond Knife Juggle',
  // 43: 'Opal Knife Juggle',
  // 44: 'Sapphire Knife Juggle',
  // 45: 'Ruby Knife Juggle',
  // 46: 'Garnet Knife Juggle',
  // 47: 'Emerald Knife Juggle',
  // 48: 'Assassinate',
  // 49: 'Diamond Assassinate',
  // 50: 'Opal Assassinate',
  // 51: 'Sapphire Assassinate',
  // 52: 'Ruby Assassinate',
  // 53: 'Garnet Assassinate',
  // 54: 'Emerald Assassinate',
  // 55: 'Shadowstep',
  // 56: 'Diamond Shadowstep',
  // 57: 'Opal Shadowstep',
  // 58: 'Sapphire Shadowstep',
  // 59: 'Ruby Shadowstep',
  // 60: 'Garnet Shadowstep',
  // 61: 'Emerald Shadowstep',
  // 62: 'Full Moon',
  // 63: 'Diamond Full Moon',
  // 64: 'Opal Full Moon',
  // 65: 'Sapphire Full Moon',
  // 66: 'Ruby Full Moon',
  // 67: 'Garnet Full Moon',
  // 68: 'Emerald Full Moon',
  // 69: 'Dark Wave',
  // 70: 'Diamond Dark Wave',
  // 71: 'Opal Dark Wave',
  // 72: 'Sapphire Dark Wave',
  // 73: 'Ruby Dark Wave',
  // 74: 'Garnet Dark Wave',
  // 75: 'Emerald Dark Wave',
  // 76: 'Spinning Leap',
  // 77: 'Diamond Spinning Leap',
  // 78: 'Opal Spinning Leap',
  // 79: 'Sapphire Spinning Leap',
  // 80: 'Ruby Spinning Leap',
  // 81: 'Garnet Spinning Leap',
  // 82: 'Emerald Spinning Leap',
  // 83: 'Shadow Barrier',
  // 84: 'Diamond Shadow Barrier',
  // 85: 'Opal Shadow Barrier',
  // 86: 'Sapphire Shadow Barrier',
  // 87: 'Ruby Shadow Barrier',
  // 88: 'Garnet Shadow Barrier',
  // 89: 'Emerald Shadow Barrier',
  // 90: 'Twirling Rose',
  // 91: 'Diamond Twirling Rose',
  // 92: 'Opal Twirling Rose',
  // 93: 'Sapphire Twirling Rose',
  // 94: 'Ruby Twirling Rose',
  // 95: 'Garnet Twirling Rose',
  // 96: 'Emerald Twirling Rose',
  // 97: 'Falling Petal',
  // 98: 'Diamond Falling Petal',
  // 99: 'Opal Falling Petal',
  // 100: 'Sapphire Falling Petal',
  // 101: 'Ruby Falling Petal',
  // 102: 'Garnet Falling Petal',
  // 103: 'Emerald Falling Petal',
  // 104: 'Lily Blossom',
  // 105: 'Diamond Lily Blossom',
  // 106: 'Opal Lily Blossom',
  // 107: 'Sapphire Lily Blossom',
  // 108: 'Ruby Lily Blossom',
  // 109: 'Garnet Lily Blossom',
  // 110: 'Emerald Lily Blossom',
  // 111: 'Golden Grace',
  // 112: 'Diamond Golden Grace',
  // 113: 'Opal Golden Grace',
  // 114: 'Sapphire Golden Grace',
  // 115: 'Ruby Golden Grace',
  // 116: 'Garnet Golden Grace',
  // 117: 'Emerald Golden Grace',
  // 118: 'Dimi Life',
  // 119: 'Diamond Dimi Life',
  // 120: 'Opal Dimi Life',
  // 121: 'Sapphire Dimi Life',
  // 122: 'Ruby Dimi Life',
  // 123: 'Garnet Dimi Life',
  // 124: 'Emerald Dimi Life',
  // 125: 'Lat Life',
  // 126: 'Diamond Lat Life',
  // 127: 'Opal Lat Life',
  // 128: 'Sapphire Lat Life',
  // 129: 'Ruby Lat Life',
  // 130: 'Garnet Lat Life',
  // 131: 'Emerald Lat Life',
  // 132: 'Summon Spirit',
  // 133: 'Diamond Summon Spirit',
  // 134: 'Opal Summon Spirit',
  // 135: 'Sapphire Summon Spirit',
  // 136: 'Ruby Summon Spirit',
  // 137: 'Garnet Summon Spirit',
  // 138: 'Emerald Summon Spirit',
  // 139: "Nature's Blessing",
  // 140: "Diamond Nature's Blessing",
  // 141: "Opal Nature's Blessing",
  // 142: "Sapphire Nature's Blessing",
  // 143: "Ruby Nature's Blessing",
  // 144: "Garnet Nature's Blessing",
  // 145: "Emerald Nature's Blessing",
  // 146: 'Sword Thrust',
  // 147: 'Diamond Sword Thrust',
  // 148: 'Opal Sword Thrust',
  // 149: 'Sapphire Sword Thrust',
  // 150: 'Ruby Sword Thrust',
  // 151: 'Garnet Sword Thrust',
  // 152: 'Emerald Sword Thrust',
  // 153: 'Siphon Spell',
  // 154: 'Diamond Siphon Spell',
  // 155: 'Opal Siphon Spell',
  // 156: 'Sapphire Siphon Spell',
  // 157: 'Ruby Siphon Spell',
  // 158: 'Garnet Siphon Spell',
  // 159: 'Emerald Siphon Spell',
  // 160: 'Magicked Fleche',
  // 161: 'Diamond Magicked Fleche',
  // 162: 'Opal Magicked Fleche',
  // 163: 'Sapphire Magicked Fleche',
  // 164: 'Ruby Magicked Fleche',
  // 165: 'Garnet Magicked Fleche',
  // 166: 'Emerald Magicked Fleche',
  // 167: 'Novi Dark',
  // 168: 'Diamond Novi Dark',
  // 169: 'Opal Novi Dark',
  // 170: 'Sapphire Novi Dark',
  // 171: 'Ruby Novi Dark',
  // 172: 'Garnet Novi Dark',
  // 173: 'Emerald Novi Dark',
  // 174: 'Arrowshot',
  // 175: 'Diamond Arrowshot',
  // 176: 'Opal Arrowshot',
  // 177: 'Sapphire Arrowshot',
  // 178: 'Ruby Arrowshot',
  // 179: 'Garnet Arrowshot',
  // 180: 'Emerald Arrowshot',
  // 181: 'Rabbitsnare',
  // 182: 'Diamond Rabbitsnare',
  // 183: 'Opal Rabbitsnare',
  // 184: 'Sapphire Rabbitsnare',
  // 185: 'Ruby Rabbitsnare',
  // 186: 'Garnet Rabbitsnare',
  // 187: 'Emerald Rabbitsnare',
  // 188: 'Barrage',
  // 189: 'Diamond Barrage',
  // 190: 'Opal Barrage',
  // 191: 'Sapphire Barrage',
  // 192: 'Ruby Barrage',
  // 193: 'Garnet Barrage',
  // 194: 'Emerald Barrage',
  // 195: 'Careful Aim',
  // 196: 'Diamond Careful Aim',
  // 197: 'Opal Careful Aim',
  // 198: 'Sapphire Careful Aim',
  // 199: 'Ruby Careful Aim',
  // 200: 'Garnet Careful Aim',
  // 201: 'Emerald Careful Aim',
  // 202: 'Flame Hook',
  // 203: 'Diamond Flame Hook',
  // 204: 'Opal Flame Hook',
  // 205: 'Sapphire Flame Hook',
  // 206: 'Ruby Flame Hook',
  // 207: 'Garnet Flame Hook',
  // 208: 'Emerald Flame Hook',
  // 209: 'Quick Jab',
  // 210: 'Diamond Quick Jab',
  // 211: 'Opal Quick Jab',
  // 212: 'Sapphire Quick Jab',
  // 213: 'Ruby Quick Jab',
  // 214: 'Garnet Quick Jab',
  // 215: 'Emerald Quick Jab',
  // 216: 'Fury',
  // 217: 'Diamond Fury',
  // 218: 'Opal Fury',
  // 219: 'Sapphire Fury',
  // 220: 'Ruby Fury',
  // 221: 'Garnet Fury',
  // 222: 'Emerald Fury',
  // 223: 'Footwork',
  // 224: 'Diamond Footwork',
  // 225: 'Opal Footwork',
  // 226: 'Sapphire Footwork',
  // 227: 'Ruby Footwork',
  // 228: 'Garnet Footwork',
  // 229: 'Emerald Footwork',
  // 230: 'Spear Thrust',
  // 231: 'Diamond Spear Thrust',
  // 232: 'Opal Spear Thrust',
  // 233: 'Sapphire Spear Thrust',
  // 234: 'Ruby Spear Thrust',
  // 235: 'Garnet Spear Thrust',
  // 236: 'Emerald Spear Thrust',
  // 237: 'Lat Holy',
  // 238: 'Diamond Lat Holy',
  // 239: 'Opal Lat Holy',
  // 240: 'Sapphire Lat Holy',
  // 241: 'Ruby Lat Holy',
  // 242: 'Garnet Lat Holy',
  // 243: 'Emerald Lat Holy',
  // 244: 'Novi Holy',
  // 245: 'Diamond Novi Holy',
  // 246: 'Opal Novi Holy',
  // 247: 'Sapphire Novi Holy',
  // 248: 'Ruby Novi Holy',
  // 249: 'Garnet Novi Holy',
  // 250: 'Emerald Novi Holy',
  // 251: 'Roll & Phalanx',
  // 252: 'Diamond Roll & Phalanx',
  // 253: 'Opal Roll & Phalanx',
  // 254: 'Sapphire Roll & Phalanx',
  // 255: 'Ruby Roll & Phalanx',
  // 256: 'Garnet Roll & Phalanx',
  // 257: 'Emerald Roll & Phalanx',
  // 258: 'Strike Command',
  // 259: 'Diamond Strike Command',
  // 260: 'Opal Strike Command',
  // 261: 'Sapphire Strike Command',
  // 262: 'Ruby Strike Command',
  // 263: 'Garnet Strike Command',
  // 264: 'Emerald Strike Command',
  // 265: 'March Command',
  // 266: 'Diamond March Command',
  // 267: 'Opal March Command',
  // 268: 'Sapphire March Command',
  // 269: 'Ruby March Command',
  // 270: 'Garnet March Command',
  // 271: 'Emerald March Command',
  // 272: 'Abyssal Call',
  // 273: 'Diamond Abyssal Call',
  // 274: 'Opal Abyssal Call',
  // 275: 'Sapphire Abyssal Call',
  // 276: 'Ruby Abyssal Call',
  // 277: 'Garnet Abyssal Call',
  // 278: 'Emerald Abyssal Call',
  // 279: 'Protect Command',
  // 280: 'Diamond Protect Command',
  // 281: 'Opal Protect Command',
  // 282: 'Sapphire Protect Command',
  // 283: 'Ruby Protect Command',
  // 284: 'Garnet Protect Command',
  // 285: 'Emerald Protect Command',
  // 286: 'Rabbitsmash',
  // 287: 'Diamond Rabbitsmash',
  // 288: 'Opal Rabbitsmash',
  // 289: 'Sapphire Rabbitsmash',
  // 290: 'Ruby Rabbitsmash',
  // 291: 'Garnet Rabbitsmash',
  // 292: 'Emerald Rabbitsmash',
  // 293: 'Step & Swing',
  // 294: 'Diamond Step & Swing',
  // 295: 'Opal Step & Swing',
  // 296: 'Sapphire Step & Swing',
  // 297: 'Ruby Step & Swing',
  // 298: 'Garnet Step & Swing',
  // 299: 'Emerald Step & Swing',
  // 300: 'Doublesmash',
  // 301: 'Diamond Doublesmash',
  // 302: 'Opal Doublesmash',
  // 303: 'Sapphire Doublesmash',
  // 304: 'Ruby Doublesmash',
  // 305: 'Garnet Doublesmash',
  // 306: 'Emerald Doublesmash',
  // 307: 'Wheel Swing',
  // 308: 'Diamond Wheel Swing',
  // 309: 'Opal Wheel Swing',
  // 310: 'Sapphire Wheel Swing',
  // 311: 'Ruby Wheel Swing',
  // 312: 'Garnet Wheel Swing',
  // 313: 'Emerald Wheel Swing',
  // 314: 'Dimi Fire',
  // 315: 'Diamond Dimi Fire',
  // 316: 'Opal Dimi Fire',
  // 317: 'Sapphire Dimi Fire',
  // 318: 'Ruby Dimi Fire',
  // 319: 'Garnet Dimi Fire',
  // 320: 'Emerald Dimi Fire',
  // 321: 'Lat Fire',
  // 322: 'Diamond Lat Fire',
  // 323: 'Opal Lat Fire',
  // 324: 'Sapphire Lat Fire',
  // 325: 'Ruby Lat Fire',
  // 326: 'Garnet Lat Fire',
  // 327: 'Emerald Lat Fire',
  // 328: 'Flare Kick',
  // 329: 'Diamond Flare Kick',
  // 330: 'Opal Flare Kick',
  // 331: 'Sapphire Flare Kick',
  // 332: 'Ruby Flare Kick',
  // 333: 'Garnet Flare Kick',
  // 334: 'Emerald Flare Kick',
  // 335: 'Smokestep',
  // 336: 'Diamond Smokestep',
  // 337: 'Opal Smokestep',
  // 338: 'Sapphire Smokestep',
  // 339: 'Ruby Smokestep',
  // 340: 'Garnet Smokestep',
  // 341: 'Emerald Smokestep',
  // 342: 'Pistolshot',
  // 343: 'Diamond Pistolshot',
  // 344: 'Opal Pistolshot',
  // 345: 'Sapphire Pistolshot',
  // 346: 'Ruby Pistolshot',
  // 347: 'Garnet Pistolshot',
  // 348: 'Emerald Pistolshot',
  // 349: 'Reload',
  // 350: 'Diamond Reload',
  // 351: 'Opal Reload',
  // 352: 'Sapphire Reload',
  // 353: 'Ruby Reload',
  // 354: 'Garnet Reload',
  // 355: 'Emerald Reload',
  // 356: 'Mixed Bomb',
  // 357: 'Diamond Mixed Bomb',
  // 358: 'Opal Mixed Bomb',
  // 359: 'Sapphire Mixed Bomb',
  // 360: 'Ruby Mixed Bomb',
  // 361: 'Garnet Mixed Bomb',
  // 362: 'Emerald Mixed Bomb',
  // 363: 'Take Cover',
  // 364: 'Diamond Take Cover',
  // 365: 'Opal Take Cover',
  // 366: 'Sapphire Take Cover',
  // 367: 'Ruby Take Cover',
  // 368: 'Garnet Take Cover',
  // 369: 'Emerald Take Cover',
  // 370: 'Anger',
  // 371: 'Diamond Anger',
  // 372: 'Opal Anger',
  // 373: 'Sapphire Anger',
  // 374: 'Ruby Anger',
  // 375: 'Garnet Anger',
  // 376: 'Emerald Anger',
  // 377: 'Envy',
  // 378: 'Diamond Envy',
  // 379: 'Opal Envy',
  // 380: 'Sapphire Envy',
  // 381: 'Ruby Envy',
  // 382: 'Garnet Envy',
  // 383: 'Emerald Envy',
  // 384: 'Sadness',
  // 385: 'Diamond Sadness',
  // 386: 'Opal Sadness',
  // 387: 'Sapphire Sadness',
  // 388: 'Ruby Sadness',
  // 389: 'Garnet Sadness',
  // 390: 'Emerald Sadness',
  // 391: 'Panic',
  // 392: 'Diamond Panic',
  // 393: 'Opal Panic',
  // 394: 'Sapphire Panic',
  // 395: 'Ruby Panic',
  // 396: 'Garnet Panic',
  // 397: 'Emerald Panic',
  // 398: '???',
  399: 'Raven Grimoire',
  400: 'Blackwing Staff',
  401: 'Curse Talon',
  402: 'Darkmagic Blade',
  403: "Witch's Cloak",
  404: 'Crowfeather Hairpin',
  405: 'Redblack Ribbon',
  406: 'Opal Necklace',
  407: 'Sleeping Greatbow',
  408: 'Crescentmoon Dagger',
  409: 'Lullaby Harp',
  410: 'Nightstar Grimoire',
  411: 'Moon Pendant',
  412: 'Pajama Hat',
  413: 'Stuffed Rabbit',
  414: 'Nightingale Gown',
  415: 'Eternity Flute',
  416: 'Timewarp Wand',
  417: 'Chrome Shield',
  418: 'Clockwork Tome',
  419: 'Metronome Boots',
  420: 'Timemage Cap',
  421: 'Starry Cloak',
  422: 'Gemini Necklace',
  423: 'Hawkfeather Fan',
  424: 'Windbite Dagger',
  425: 'Pidgeon Bow',
  426: 'Shinsoku Katana',
  427: 'Eaglewing Charm',
  428: 'Sparrow Feather',
  429: 'Winged Cap',
  430: "Thief's Coat",
  431: 'Vampiric Dagger',
  432: 'Bloody Bandage',
  433: 'Leech Staff',
  434: 'Bloodhound Greatsword',
  435: 'Reaper Cloak',
  436: 'Bloodflower Brooch',
  437: 'Wolf Hood',
  438: 'Blood Vial',
  439: 'Black Wakizashi',
  440: 'Throwing Dagger',
  441: "Assassin's Knife",
  442: 'Ninjutsu Scroll',
  443: 'Shadow Bracelet',
  444: 'Ninja Robe',
  445: 'Kunoichi Hood',
  446: 'Shinobi Tabi',
  447: 'Dragonhead Spear',
  448: 'Granite Greatsword',
  449: 'Greysteel Shield',
  450: 'Stonebreaker Staff',
  451: 'Tough Gauntlet',
  452: 'Rockdragon Mail',
  453: 'Obsidian Hairpin',
  454: 'Iron Greaves',
  455: 'Volcano Spear',
  456: 'Reddragon Blade',
  457: 'Flame Bow',
  458: 'Meteor Staff',
  459: 'Phoenix Charm',
  460: 'Firescale Corset',
  461: 'Demon Horns',
  462: 'Flamewalker Boots',
  463: 'Diamond Shield',
  464: 'Peridot Rapier',
  465: 'Garnet Staff',
  466: 'Sapphire Violin',
  467: 'Emerald Chestplate',
  468: 'Amethyst Bracelet',
  469: 'Topaz Charm',
  470: 'Ruby Circlet',
  471: 'Brightstorm Spear',
  472: 'Bolt Staff',
  473: 'Lightning Bow',
  474: 'Darkstorm Knife',
  475: 'Darkcloud Necklace',
  476: 'Crown of Storms',
  477: 'Thunderclap Gloves',
  478: 'Storm Petticoat',
  479: 'Holy Greatsword',
  480: 'Sacred Bow',
  481: 'Purification Rod',
  482: 'Ornamental Bell',
  483: "Shrinemaiden's Kosode",
  484: 'Redwhite Ribbon',
  485: 'Divine Mirror',
  486: 'Golden Chime',
  487: 'Book of Cheats',
  488: 'Golden Katana',
  489: 'Glittering Trumpet',
  490: 'Royal Staff',
  491: 'Ballroom Gown',
  492: 'Silver Coin',
  493: "Queen's Crown",
  494: 'Mimick Rabbitfoot',
  495: 'Butterfly Ocarina',
  496: 'Fairy Spear',
  497: 'Moss Shield',
  498: 'Floral Bow',
  499: 'Blue Rose',
  500: 'Sunflower Crown',
  501: 'Midsummer Dress',
  502: 'Grasswoven Bracelet',
  503: 'Snakefang Dagger',
  504: 'Ivy Staff',
  505: 'Deathcap Tome',
  506: 'Spiderbite Bow',
  507: 'Compound Gloves',
  508: 'Poisonfrog Charm',
  509: 'Venom Hood',
  510: "Chemist's Coat",
  511: 'Seashell Shield',
  512: 'Necronomicon',
  513: 'Tidal Greatsword',
  514: 'Occult Dagger',
  515: 'Mermaid Scalemail',
  516: 'Hydrous Blob',
  517: 'Abyss Artifact',
  518: 'Lost Pendant',
  519: 'Sawtooth Cleaver',
  520: "Raven's Dagger",
  521: 'Killing Note',
  522: 'Blacksteel Buckler',
  523: 'Nightguard Gloves',
  524: "Sniper's Eyeglasses",
  525: 'Darkmage Charm',
  526: 'Firststrike Bracelet',
  527: 'Obsidian Rod',
  528: 'Darkglass Spear',
  529: 'Timespace Dagger',
  530: 'Quartz Shield',
  531: 'Pocketwatch',
  532: 'Nova Crown',
  533: 'Blackhole Charm',
  534: 'Twinstar Earrings',
  535: 'Kyou No Omikuji',
  536: 'Youkai Bracelet',
  537: 'Oni Staff',
  538: 'Kappa Shield',
  539: 'Usagi Kamen',
  540: 'Red Tanzaku',
  541: 'Vega Spear',
  542: 'Altair Dagger',
  543: 'Ghost Spear',
  544: 'Phantom Dagger',
  545: 'Cursed Candlestaff',
  546: 'Haunted Gloves',
  547: 'Old Bonnet',
  548: 'Maid Outfit',
  549: 'Calling Bell',
  550: 'Smoke Shield',
  551: 'Grandmaster Spear',
  552: 'Teacher Knife',
  553: 'Tactician Rod',
  554: 'Spiked Shield',
  555: 'Battlemaiden Armor',
  556: 'Gladiator Helmet',
  557: 'Lancer Gauntlets',
  558: 'Lion Charm',
  559: 'Bluebolt Staff',
  560: 'Lapis Sword',
  561: 'Shockwave Tome',
  562: 'Battery Shield',
  563: 'Raiju Crown',
  564: 'Staticshock Earrings',
  565: 'Stormdance Gown',
  566: 'Blackbolt Ribbon',
  567: 'Crane Katana',
  568: 'Falconfeather Dagger',
  569: 'Tornado Staff',
  570: 'Cloud Guard',
  571: 'Hermes Bow',
  572: 'Talon Charm',
  573: 'Tiny Wings',
  574: 'Feathered Overcoat',
  575: 'Sandpriestess Spear',
  576: 'Flamedancer Dagger',
  577: 'Whiteflame Staff',
  578: 'Sacred Shield',
  579: 'Marble Clasp',
  580: 'Sun Pendant',
  581: 'Tiny Hourglass',
  582: 'Desert Earrings',
  583: 'Giant Stone Club',
  584: 'Ruins Sword',
  585: 'Mountain Staff',
  586: 'Boulder Shield',
  587: "Golem's Claymore",
  588: 'Stoneplate Armor',
  589: 'Sacredstone Charm',
  590: 'Clay Rabbit',
  591: 'Waterfall Polearm',
  592: 'Vorpal Dao',
  593: 'Jade Staff',
  594: 'Reflection Shield',
  595: 'Butterfly Hairpin',
  596: 'Watermage Pendant',
  597: 'Raindrop Earrings',
  598: 'Aquamarine Bracelet',
  599: 'Glacier Spear',
  600: 'Frost Dagger',
  601: 'Frozen Staff',
  602: 'Coldsteel Shield',
  603: 'Polar Coat',
  604: 'Icicle Earrings',
  605: 'Winter Hat',
  606: 'Snow Boots',
  607: 'Spear of Remorse',
  608: 'Memory Greatsword',
  609: 'Staff of Sorrow',
  610: 'Shield of Smiles',
  611: 'Lonesome Pendant',
  612: 'Spark of Determination',
  613: 'Crown of Love',
  614: 'Comforting Coat',
  615: 'Righthand Cast',
  616: 'Lefthand Cast',
  617: 'Hexed Blindfold',
  618: "Angel's Halo",
  619: 'Unsacred Pendant',
  620: 'Whitewing Bracelet',
  621: 'Darkcrystal Rose',
  622: 'Dark Wings',
  623: 'Giant Paintbrush',
  624: 'Sewing Sword',
  625: 'Sketchbook',
  626: 'Palette Shield',
  627: 'Handmade Charm',
  628: "Painter's Beret",
  629: 'Artist Smock',
  630: 'Colorful Earrings',
  631: 'Daylight Sword',
  632: 'Nightgleam Sword',
  633: 'Spear of Winds',
  634: 'Spear of Rains',
  635: "Heaven's Codex",
  636: "Hell's Codex",
  637: 'Robe of Light',
  638: 'Robe of Dark',
  639: 'Hooked Staff',
  640: 'Springloaded Scythe',
  641: 'Hidden Blade',
  642: 'Sharpedged Shield',
  643: 'Pointed Ring',
  644: 'Crown of Swords',
  645: 'Bladed Cloak',
  646: 'Greatsword Pendant',
  647: 'Rusted Greatsword',
  648: 'Sand Shovel',
  649: 'Saltwater Staff',
  650: 'Large Umbrella',
  651: 'Onepiece Swimsuit',
  652: 'Straw Hat',
  653: 'Large Anchor',
  654: 'Beach Sandals',
  655: "Strongman's Bar",
  656: 'Spinning Chakram',
  657: 'Ribboned Staff',
  658: 'Trick Shield',
  659: 'Rosered Leotard',
  660: "Jester's Hat",
  661: 'Rainbow Cape',
  662: "Performer's Shoes",
  663: 'Iron Pickaxe',
  664: 'Dynamite Staff',
  665: 'Fossil Dagger',
  666: 'Drill Shield',
  667: 'Canary Charm',
  668: 'Pyrite Earrings',
  669: "Caver's Cloak",
  670: "Miner's Headlamp",
  671: 'Tiny Fork',
  672: 'Stirring Spoon',
  673: 'Fanciful Book',
  674: 'Apple Plate',
  675: 'Vanilla Wafers',
  676: 'Caramel Tea',
  677: 'Strawberry Cake',
  678: 'Sweet Taffy',
  // 679: 'Full Heal',
  // 680: 'Level Up',
  // 681: 'Regeneration Potion',
  // 682: 'Essence of Spell',
  // 683: 'Darkness Potion',
  // 684: 'Quickening Potion',
  // 685: 'Winged Potion',
  // 686: 'Essence of Wit',
  // 687: 'Swifthand Potion',
  // 688: 'Fire Potion',
  // 689: 'Essence of Strength',
  // 690: 'Golden Potion',
  // 691: 'Luck Potion',
  // 692: 'Essence of Steel',
  // 693: 'Evasion Potion',
  // 694: 'Longarm Potion',
  // 695: 'Vitality Potion',
  // 696: 'Experimental Potion',
  // 697: 'Opal Primary Upgrade',
  // 698: 'Opal Secondary Upgrade',
  // 699: 'Opal Special Upgrade',
  // 700: 'Opal Defensive Upgrade',
  // 701: 'Sapphire Primary Upgrade',
  // 702: 'Sapphire Secondary Upgrade',
  // 703: 'Sapphire Special Upgrade',
  // 704: 'Sapphire Defensive Upgrade',
  // 705: 'Ruby Primary Upgrade',
  // 706: 'Ruby Secondary Upgrade',
  // 707: 'Ruby Special Upgrade',
  // 708: 'Ruby Defensive Upgrade',
  // 709: 'Garnet Primary Upgrade',
  // 710: 'Garnet Secondary Upgrade',
  // 711: 'Garnet Special Upgrade',
  // 712: 'Garnet Defensive Upgrade',
  // 713: 'Emerald Primary Upgrade',
  // 714: 'Emerald Secondary Upgrade',
  // 715: 'Emerald Special Upgrade',
  // 716: 'Emerald Defensive Upgrade'
};

// Split out copy of potion names
const potionMap = new Map(
	Object.entries({
	  681: 'Regeneration Potion',
	  682: 'Essence of Spell',
	  683: 'Darkness Potion',
	  684: 'Quickening Potion',
	  685: 'Winged Potion',
	  686: 'Essence of Wit',
	  687: 'Swifthand Potion',
	  688: 'Fire Potion',
	  689: 'Essence of Strength',
	  690: 'Golden Potion',
	  691: 'Luck Potion',
	  692: 'Essence of Steel',
	  693: 'Evasion Potion',
	  694: 'Longarm Potion',
	  695: 'Vitality Potion',
	  // 696: 'Experimental Potion',
	})
);

const potionIconMap = {
	681: 'Regeneration_Potion',
	682: 'Essence_of_Spell',
	683: 'Darkness_Potion',
	684: 'Quickening_Potion',
	685: 'Winged_Potion',
	686: 'Essence_of_Wit',
	687: 'Swifthand_Potion',
	688: 'Fire_Potion',
	689: 'Essence_of_Strength',
	690: 'Golden_Potion',
	691: 'Luck_Potion',
	692: 'Essence_of_Steel',
	693: 'Evasion_Potion',
	694: 'Longarm_Potion',
	695: 'Vitality_Potion'
	// 696: 'Experimental Potion',
};

// Modified names for cleaner display
const gemMap = new Map(
	Object.entries({
	  697: 'Opal Primary',
	  698: 'Opal Secondary',
	  699: 'Opal Special',
	  700: 'Opal Defensive',
	  701: 'Sapphire Primary',
	  702: 'Sapphire Secondary',
	  703: 'Sapphire Special',
	  704: 'Sapphire Defensive',
	  705: 'Ruby Primary',
	  706: 'Ruby Secondary',
	  707: 'Ruby Special',
	  708: 'Ruby Defensive',
	  709: 'Garnet Primary',
	  710: 'Garnet Secondary',
	  711: 'Garnet Special',
	  712: 'Garnet Defensive',
	  713: 'Emerald Primary',
	  714: 'Emerald Secondary',
	  715: 'Emerald Special',
	  716: 'Emerald Defensive'
	})
);
// Evil
const gemKeyMap = new Map(
	Object.entries({
	  697: 'opal',
	  698: 'opal',
	  699: 'opal',
	  700: 'opal',
	  701: 'sapphire',
	  702: 'sapphire',
	  703: 'sapphire',
	  704: 'sapphire',
	  705: 'ruby',
	  706: 'ruby',
	  707: 'ruby',
	  708: 'ruby',
	  709: 'garnet',
	  710: 'garnet',
	  711: 'garnet',
	  712: 'garnet',
	  713: 'emerald',
	  714: 'emerald',
	  715: 'emerald',
	  716: 'emerald'
	})
);

const idItemMap = new Map(Object.entries(itemObj));
const itemIdMap = new Map(Object.entries(itemObj).map(([id, item]) => [item, id]));

export const itemList = Object.values(itemObj);

export function name_to_id(name: string): number {
	return Number(itemIdMap.get(name) ?? 0);
}

export function id_to_name(id: number): string {
	return idItemMap.get(String(id)) ?? 'ERROR_ITEM';
}

export function id_to_potion(id: number): string {
	return potionMap.get(String(id)) ?? 'ERROR_POTION';
}

export function id_to_potion_icon(id: number): string {
	if (!(id in potionIconMap)) return 'ERROR_ICON';
	return potionIconMap[id as keyof typeof potionIconMap];
}

// skill_index referring to the skill (primary, secondary, special, defensive), starting at 0
export function gem_to_id(gem: string, skill_index: number): number | undefined {
	let gem_index: number;
	switch (gem) {
		case 'Opal':
			gem_index = 0;
			break;
		case 'Sapphire':
			gem_index = 1;
			break;
		case 'Ruby':
			gem_index = 2;
			break;
		case 'Garnet':
			gem_index = 3;
			break;
		case 'Emerald':
			gem_index = 4;
			break;
		default:
			return undefined;
	}
	return 697 + gem_index * 4 + skill_index;
}

export function id_to_gem(id: number): string {
	return gemMap.get(String(id)) ?? 'ERROR_GEM';
}

export function id_to_gem_key(id: number): string {
	return gemKeyMap.get(String(id)) ?? 'ERROR_GEM';
}

const gemKeyIconMap = {
	697: 'Spr_upgrade_purple_0',
	698: 'Spr_upgrade_purple_1',
	699: 'Spr_upgrade_purple_2',
	700: 'Spr_upgrade_purple_3',
	701: 'Spr_upgrade_blue_0',
	702: 'Spr_upgrade_blue_1',
	703: 'Spr_upgrade_blue_2',
	704: 'Spr_upgrade_blue_3',
	705: 'Spr_upgrade_red_0',
	706: 'Spr_upgrade_red_1',
	707: 'Spr_upgrade_red_2',
	708: 'Spr_upgrade_red_3',
	709: 'Spr_upgrade_yellow_0',
	710: 'Spr_upgrade_yellow_1',
	711: 'Spr_upgrade_yellow_2',
	712: 'Spr_upgrade_yellow_3',
	713: 'Spr_upgrade_green_0',
	714: 'Spr_upgrade_green_1',
	715: 'Spr_upgrade_green_2',
	716: 'Spr_upgrade_green_3'
};

export function id_to_gem_icon(id: number): string {
	if (!(id in gemKeyIconMap)) return 'ERROR_ICON';
	return gemKeyIconMap[id as keyof typeof gemKeyIconMap];
}

// TODO
// yay icon map!! Thanks to babit_ from the RnS Discord for this
const itemIconMap = new Map(
	Object.entries({
		399: "spr_item_arcane_0",
		400: "spr_item_arcane_1",
		401: "spr_item_arcane_2",
		402: "spr_item_arcane_3",
		403: "spr_item_arcane_4",
		404: "spr_item_arcane_5",
		405: "spr_item_arcane_6",
		406: "spr_item_arcane_7",
		407: "spr_item_night_0",
		408: "spr_item_night_1",
		409: "spr_item_night_2",
		410: "spr_item_night_3",
		411: "spr_item_night_4",
		412: "spr_item_night_5",
		413: "spr_item_night_6",
		414: "spr_item_night_7",
		415: "spr_item_timespace_0",
		416: "spr_item_timespace_1",
		417: "spr_item_timespace_2",
		418: "spr_item_timespace_3",
		419: "spr_item_timespace_4",
		420: "spr_item_timespace_5",
		421: "spr_item_timespace_6",
		422: "spr_item_timespace_7",
		423: "spr_item_wind_0",
		424: "spr_item_wind_1",
		425: "spr_item_wind_2",
		426: "spr_item_wind_3",
		427: "spr_item_wind_4",
		428: "spr_item_wind_5",
		429: "spr_item_wind_6",
		430: "spr_item_wind_7",
		431: "spr_item_bloodwolf_0",
		432: "spr_item_bloodwolf_1",
		433: "spr_item_bloodwolf_2",
		434: "spr_item_bloodwolf_3",
		435: "spr_item_bloodwolf_4",
		436: "spr_item_bloodwolf_5",
		437: "spr_item_bloodwolf_6",
		438: "spr_item_bloodwolf_7",
		439: "spr_item_assassin_0",
		440: "spr_item_assassin_1",
		441: "spr_item_assassin_2",
		442: "spr_item_assassin_3",
		443: "spr_item_assassin_4",
		444: "spr_item_assassin_5",
		445: "spr_item_assassin_6",
		446: "spr_item_assassin_7",
		447: "spr_item_rockdragon_0",
		448: "spr_item_rockdragon_1",
		449: "spr_item_rockdragon_2",
		450: "spr_item_rockdragon_3",
		451: "spr_item_rockdragon_4",
		452: "spr_item_rockdragon_5",
		453: "spr_item_rockdragon_6",
		454: "spr_item_rockdragon_7",
		455: "spr_item_flame_0",
		456: "spr_item_flame_1",
		457: "spr_item_flame_2",
		458: "spr_item_flame_3",
		459: "spr_item_flame_4",
		460: "spr_item_flame_5",
		461: "spr_item_flame_6",
		462: "spr_item_flame_7",
		463: "spr_item_gem_0",
		464: "spr_item_gem_1",
		465: "spr_item_gem_2",
		466: "spr_item_gem_3",
		467: "spr_item_gem_4",
		468: "spr_item_gem_5",
		469: "spr_item_gem_6",
		470: "spr_item_gem_7",
		471: "spr_item_lightning_0",
		472: "spr_item_lightning_1",
		473: "spr_item_lightning_2",
		474: "spr_item_lightning_3",
		475: "spr_item_lightning_4",
		476: "spr_item_lightning_5",
		477: "spr_item_lightning_6",
		478: "spr_item_lightning_7",
		479: "spr_item_shrine_0",
		480: "spr_item_shrine_1",
		481: "spr_item_shrine_2",
		482: "spr_item_shrine_3",
		483: "spr_item_shrine_4",
		484: "spr_item_shrine_5",
		485: "spr_item_shrine_6",
		486: "spr_item_shrine_7",
		487: "spr_item_lucky_0",
		488: "spr_item_lucky_1",
		489: "spr_item_lucky_2",
		490: "spr_item_lucky_3",
		491: "spr_item_lucky_4",
		492: "spr_item_lucky_5",
		493: "spr_item_lucky_6",
		494: "spr_item_lucky_7",
		495: "spr_item_life_0",
		496: "spr_item_life_1",
		497: "spr_item_life_2",
		498: "spr_item_life_3",
		499: "spr_item_life_4",
		500: "spr_item_life_5",
		501: "spr_item_life_6",
		502: "spr_item_life_7",
		503: "spr_item_poison_0",
		504: "spr_item_poison_1",
		505: "spr_item_poison_2",
		506: "spr_item_poison_3",
		507: "spr_item_poison_4",
		508: "spr_item_poison_5",
		509: "spr_item_poison_6",
		510: "spr_item_poison_7",
		511: "spr_item_depth_0",
		512: "spr_item_depth_1",
		513: "spr_item_depth_2",
		514: "spr_item_depth_3",
		515: "spr_item_depth_4",
		516: "spr_item_depth_5",
		517: "spr_item_depth_6",
		518: "spr_item_depth_7",
		519: "spr_item_darkbite_0",
		520: "spr_item_darkbite_1",
		521: "spr_item_darkbite_2",
		522: "spr_item_darkbite_3",
		523: "spr_item_darkbite_4",
		524: "spr_item_darkbite_5",
		525: "spr_item_darkbite_6",
		526: "spr_item_darkbite_7",
		527: "spr_item_timegem_0",
		528: "spr_item_timegem_1",
		529: "spr_item_timegem_2",
		530: "spr_item_timegem_3",
		531: "spr_item_timegem_4",
		532: "spr_item_timegem_5",
		533: "spr_item_timegem_6",
		534: "spr_item_timegem_7",
		535: "spr_item_youkai_0",
		536: "spr_item_youkai_1",
		537: "spr_item_youkai_2",
		538: "spr_item_youkai_3",
		539: "spr_item_youkai_4",
		540: "spr_item_youkai_5",
		541: "spr_item_youkai_6",
		542: "spr_item_youkai_7",
		543: "spr_item_haunted_0",
		544: "spr_item_haunted_1",
		545: "spr_item_haunted_2",
		546: "spr_item_haunted_3",
		547: "spr_item_haunted_4",
		548: "spr_item_haunted_5",
		549: "spr_item_haunted_6",
		550: "spr_item_haunted_7",
		551: "spr_item_gladiator_0",
		552: "spr_item_gladiator_1",
		553: "spr_item_gladiator_2",
		554: "spr_item_gladiator_3",
		555: "spr_item_gladiator_4",
		556: "spr_item_gladiator_5",
		557: "spr_item_gladiator_6",
		558: "spr_item_gladiator_7",
		559: "spr_item_sparkblade_0",
		560: "spr_item_sparkblade_1",
		561: "spr_item_sparkblade_2",
		562: "spr_item_sparkblade_3",
		563: "spr_item_sparkblade_4",
		564: "spr_item_sparkblade_5",
		565: "spr_item_sparkblade_6",
		566: "spr_item_sparkblade_7",
		567: "spr_item_swiftflight_0",
		568: "spr_item_swiftflight_1",
		569: "spr_item_swiftflight_2",
		570: "spr_item_swiftflight_3",
		571: "spr_item_swiftflight_4",
		572: "spr_item_swiftflight_5",
		573: "spr_item_swiftflight_6",
		574: "spr_item_swiftflight_7",
		575: "spr_item_sacredflame_0",
		576: "spr_item_sacredflame_1",
		577: "spr_item_sacredflame_2",
		578: "spr_item_sacredflame_3",
		579: "spr_item_sacredflame_4",
		580: "spr_item_sacredflame_5",
		581: "spr_item_sacredflame_6",
		582: "spr_item_sacredflame_7",
		583: "spr_item_ruins_0",
		584: "spr_item_ruins_1",
		585: "spr_item_ruins_2",
		586: "spr_item_ruins_3",
		587: "spr_item_ruins_4",
		588: "spr_item_ruins_5",
		589: "spr_item_ruins_6",
		590: "spr_item_ruins_7",
		591: "spr_item_lakeshrine_0",
		592: "spr_item_lakeshrine_1",
		593: "spr_item_lakeshrine_2",
		594: "spr_item_lakeshrine_3",
		595: "spr_item_lakeshrine_4",
		596: "spr_item_lakeshrine_5",
		597: "spr_item_lakeshrine_6",
		598: "spr_item_lakeshrine_7",
		599: "spr_item_glacier_0",
		600: "spr_item_glacier_1",
		601: "spr_item_glacier_2",
		602: "spr_item_glacier_3",
		603: "spr_item_glacier_4",
		604: "spr_item_glacier_5",
		605: "spr_item_glacier_6",
		606: "spr_item_glacier_7",
		607: "spr_item_memory_0",
		608: "spr_item_memory_1",
		609: "spr_item_memory_2",
		610: "spr_item_memory_3",
		611: "spr_item_memory_4",
		612: "spr_item_memory_5",
		613: "spr_item_memory_6",
		614: "spr_item_memory_7",
		615: "spr_item_cultist_0",
		616: "spr_item_cultist_1",
		617: "spr_item_cultist_2",
		618: "spr_item_cultist_3",
		619: "spr_item_cultist_4",
		620: "spr_item_cultist_5",
		621: "spr_item_cultist_6",
		622: "spr_item_cultist_7",
		623: "spr_item_painters_0",
		624: "spr_item_painters_1",
		625: "spr_item_painters_2",
		626: "spr_item_painters_3",
		627: "spr_item_painters_4",
		628: "spr_item_painters_5",
		629: "spr_item_painters_6",
		630: "spr_item_painters_7",
		631: "spr_item_daynight_0",
		632: "spr_item_daynight_1",
		633: "spr_item_daynight_2",
		634: "spr_item_daynight_3",
		635: "spr_item_daynight_4",
		636: "spr_item_daynight_5",
		637: "spr_item_daynight_6",
		638: "spr_item_daynight_7",
		639: "spr_item_sharpedge_0",
		640: "spr_item_sharpedge_1",
		641: "spr_item_sharpedge_2",
		642: "spr_item_sharpedge_3",
		643: "spr_item_sharpedge_4",
		644: "spr_item_sharpedge_5",
		645: "spr_item_sharpedge_6",
		646: "spr_item_sharpedge_7",
		647: "spr_item_oceans_0",
		648: "spr_item_oceans_1",
		649: "spr_item_oceans_2",
		650: "spr_item_oceans_3",
		651: "spr_item_oceans_4",
		652: "spr_item_oceans_5",
		653: "spr_item_oceans_6",
		654: "spr_item_oceans_7",
		655: "spr_item_performers_0",
		656: "spr_item_performers_1",
		657: "spr_item_performers_2",
		658: "spr_item_performers_3",
		659: "spr_item_performers_4",
		660: "spr_item_performers_5",
		661: "spr_item_performers_6",
		662: "spr_item_performers_7",
		663: "spr_item_miners_0",
		664: "spr_item_miners_1",
		665: "spr_item_miners_2",
		666: "spr_item_miners_3",
		667: "spr_item_miners_4",
		668: "spr_item_miners_5",
		669: "spr_item_miners_6",
		670: "spr_item_miners_7",
		671: "spr_item_teaparty_0",
		672: "spr_item_teaparty_1",
		673: "spr_item_teaparty_2",
		674: "spr_item_teaparty_3",
		675: "spr_item_teaparty_4",
		676: "spr_item_teaparty_5",
		677: "spr_item_teaparty_6",
		678: "spr_item_teaparty_7",
	})
);

export function id_to_icon(id: number): string {
	return itemIconMap.get(String(id)) ?? 'ERROR_ICON';
}

// The monster type :3
export type SeedData = [
	id: number,
	area1: number,
	area2: number,
	area3: number,
	area4: number,
	area5: number,
	item1_1: number, // Chest 1
	item1_2: number,
	item1_3: number,
	item1_4: number,
	item1_5: number,
	item2_1: number, // Chest 2
	item2_2: number,
	item2_3: number,
	item2_4: number,
	item2_5: number,
	item3_1: number, // Chest 3
	item3_2: number,
	item3_3: number,
	item3_4: number,
	item3_5: number,
	item4_1: number, // Chest 4
	item4_2: number,
	item4_3: number,
	item4_4: number,
	item4_5: number,
	item5_1: number, // Chest 5
	item5_2: number,
	item5_3: number,
	item5_4: number,
	item5_5: number,
	item6_1: number, // Chest 6
	item6_2: number,
	item6_3: number,
	item6_4: number,
	item6_5: number,
	shop_1_p_1_id: number, // Shop 1, potion IDs
	shop_1_p_2_id: number,
	shop_1_p_3_id: number,
	shop_1_p_1_price: number, // Potion prices
	shop_1_p_2_price: number,
	shop_1_p_3_price: number,
	shop_1_g_1_id: number, // Gems, prices
	shop_1_g_1_price: number,
	shop_1_g_2_id: number,
	shop_1_g_2_price: number,
	shop_1_g_3_id: number,
	shop_1_g_3_price: number,
	shop_1_g_4_id: number,
	shop_1_g_4_price: number,
	shop_2_p_1_id: number, // Shop 2, potion IDs
	shop_2_p_2_id: number,
	shop_2_p_3_id: number,
	shop_2_p_1_price: number, // Potion prices
	shop_2_p_2_price: number,
	shop_2_p_3_price: number,
	shop_2_g_1_id: number, // Gems, prices
	shop_2_g_1_price: number,
	shop_2_g_2_id: number,
	shop_2_g_2_price: number,
	shop_2_g_3_id: number,
	shop_2_g_3_price: number,
	shop_2_g_4_id: number,
	shop_2_g_4_price: number,
	shop_3_p_1_id: number, // Shop 3, potion IDs
	shop_3_p_2_id: number,
	shop_3_p_3_id: number,
	shop_3_p_1_price: number, // Potion prices
	shop_3_p_2_price: number,
	shop_3_p_3_price: number,
	shop_3_g_1_id: number, // Gems, prices
	shop_3_g_1_price: number,
	shop_3_g_2_id: number,
	shop_3_g_2_price: number,
	shop_3_g_3_id: number,
	shop_3_g_3_price: number,
	shop_3_g_4_id: number,
	shop_3_g_4_price: number,
	shop_4_p_1_id: number, // Shop 4, potion IDs
	shop_4_p_2_id: number,
	shop_4_p_3_id: number,
	shop_4_p_1_price: number, // Potion prices
	shop_4_p_2_price: number,
	shop_4_p_3_price: number,
	shop_4_g_1_id: number, // Gems, prices
	shop_4_g_1_price: number,
	shop_4_g_2_id: number,
	shop_4_g_2_price: number,
	shop_4_g_3_id: number,
	shop_4_g_3_price: number,
	shop_4_g_4_id: number,
	shop_4_g_4_price: number,
	chest_color_1: number,
	chest_color_2: number,
	chest_color_3: number,
	chest_color_4: number,
	chest_color_5: number,
	chest_color_6: number,
];

export type GemName = ['white', 'opal', 'sapphire', 'ruby', 'garnet', 'emerald'][number];

export const areaShortNameMap = {
	0: 'hw_outskirts',
  1: 'hw_nest',
  2: 'hw_arsenal',
  3: 'hw_lighthouse',
  4: 'hw_streets',
  5: 'hw_lakeside',
  6: 'hw_keep',
  7: 'hw_geode',
  8: 'hw_sanct',
  9: 'hw_depths',
  10: 'hw_aurum',
  11: 'hw_darkhall',
	12: 'extra_moonlit_prescipice',
	13: 'extra_reflection'
};

const areaMap = {
	hw_outskirts: 'Kingdom Outskirts',
	hw_nest: "Scholar's Nest",
	hw_arsenal: "King's Aresenal",
	hw_lighthouse: 'Red Darkhouse',
	hw_streets: 'Churchmouse Streets',
	hw_lakeside: 'Emerald Lakeside',
	hw_keep: 'Pale Keep',
	hw_geode: 'Crack in the Geode',
	hw_sanct: 'Subterra Sanctum',
	hw_depths: 'Darkhouse Depths',
	hw_aurum: 'Atelier Aurum',
	hw_darkhall: 'Looping Hallway',
	extra_moonlit_prescipice: 'Moonlit Prescipice',
	extra_reflection: 'Reflecting Pool',
};

export function area_to_name(area: string): string {
	if (!(area in areaMap)) return 'ERROR_AREA';
	return areaMap[area as keyof typeof areaMap];
}

const areaIconMap = {
	hw_outskirts: 'Area_Kingdom_Outskirts',
	hw_nest: "Area_Scholar's_Nest",
	hw_arsenal: "Area_King's_Arsenal",
	hw_lighthouse: 'Area_Red_Darkhouse',
	hw_streets: 'Area_Churchmouse_Streets',
	hw_lakeside: 'Area_Emerald_Lakeside',
	hw_keep: 'Area_The_Pale_Keep',
	hw_geode: 'Area_Crack_In_The_Geode',
	hw_sanct: 'Area_Subterra_Sanctum',
	hw_depths: 'Area_Darkhouse_Depths',
	hw_aurum: 'Area_Atelier_Aurum',
	hw_darkhall: 'Area_Looping_Hallway',
	extra_moonlit_prescipice: 'Area_Moonlit_Pinnacle',
	extra_reflection: 'Area_Reflecting_Pool',
};

export function area_to_icon(area: string): string {
	if (!(area in areaIconMap)) return 'ERROR_ICON';
	return areaIconMap[area as keyof typeof areaIconMap];
}

export function starting_area_to_icon(area: number): string {
	if (area < 0 || 15 < area) return 'ERROR_ICON';
	return `starting_area_${area}.png`;
}

// TODO
const areaColorMap: Record<AreaName, string> = {
	hw_outskirts: 'white',
	hw_nest: 'opal',
	hw_arsenal: 'sapphire',
	hw_lighthouse: 'ruby',
	hw_streets: 'garnet',
	hw_lakeside: 'emerald',
	hw_pale_keep: 'white',
	hw_geode: 'white',
	hw_sanct: 'white',
	hw_depths: 'white',
	hw_aurum: 'white',
	hw_darkhall: 'white',
	extra_moonlit_prescipice: 'white',
	extra_reflection: 'white',
};

export function area_to_color(area: AreaName): string {
	return `${areaColorMap[area]}`;
}

const chestColorMap: Record<number, GemName> = {
	2: 'white',
	3: 'opal',
	4: 'sapphire',
	5: 'ruby',
	6: 'garnet',
	7: 'emerald'
};

// Displayed name
const chestColorLabelMap: Record<number, string> = {
	2: 'white',
	3: 'opal',
	4: 'sapphire',
	5: 'ruby',
	6: 'garnet',
	7: 'emerald'
};

export function chest_to_color(id: number): GemName {
	if (!(id in chestColorMap)) return 'white';
	return chestColorMap[id as keyof typeof chestColorMap];
}

export function chest_to_color_label(id: number): string {
	if (!(id in chestColorLabelMap)) return 'White';
	return chestColorLabelMap[id as keyof typeof chestColorLabelMap];
}

export const itemsets: Array<string> = [
	"arcane",
	"night",
	"timespace",
	"wind",
	"bloodwolf",
	"assassin",
	"rockdragon",
	"flame",
	"gem",
	"lightning",
	"shrine",
	"lucky",
	"life",
	"poison",
	"depth",
	"darkbite",
	"timegem",
	"youkai",
	"haunted",
	"gladiator",
	"sparkblade",
	"swiftflight",
	"sacredflame",
	"ruins",
	"lakeshrine",
	"glacier",
	"memory",
	"cultist",
	"painters",
	"daynight",
	"sharpedge",
	"oceans",
	"performers",
	"miners",
	"teaparty",
]

export const itemsetColorMap: Record<string, string> = {
	arcane: "#5735EF",
	night: "#9B5FEB",
	timespace: "#795EFF",
	wind: "#5EFDE6",
	bloodwolf: "#2740B9",
	assassin: "#3B57E3",
	rockdragon: "#CB4056",
	flame: "#F83838",
	gem: "#F05F97",
	lightning: "#FFF7B7",
	shrine: "#F1A892",
	lucky: "#FFB982",
	life: "#7EFF6B",
	poison: "#4CE67D",
	depth: "#47D38B",
	darkbite: "#5735EF",
	timegem: "#573FFF",
	youkai: "#665B66",
	haunted: "#89F9DC",
	gladiator: "#8D8180",
	sparkblade: "#3C63FF",
	swiftflight: "#41FCFF",
	sacredflame: "#FF987D",
	ruins: "#6FFFB2",
	lakeshrine: "#4BE1AB",
	glacier: "#59AAB8",
	memory: "#F05797",
	cultist: "#8146EF",
	painters: "#D8E2D6",
	daynight: "#FF7D98",
	sharpedge: "#3E3E4C",
	oceans: "#41FCFF",
	performers: "#FFE5BC",
	miners: "#76C490",
	teaparty: "#EAFF90",
}

export function itemset_index_to_icon(itemset: string, index: number): string {
	if (itemset < 0 || 8 < itemset) return 'ERROR_ICON'
	if (!itemsets.includes(itemset)) return 'ERROR_ICON'
	return `spr_item_${itemset}_${index}.webp`;
}
