// Data from the RNS Discord strats-and-steel channel

// COLUMNS
// 0 (A): Seed
// 1 (B): Area 1
// 2 (C): Area 2
// 3 (D): Area 3
// 4 (E): Area 4
// 5 (F): Area 5
// 6-10 (G-K): Chest 1
// 11-15 (L-P): Chest 2
// 16-20 (Q-U): Chest 3
// 21-25 (V-Z): Chest 4
// 26-30 (AA-AE): Chest 5
// 31-35 (AF-AJ): Chest 6
// 36-38 (AK-AM): Shop 1 Potions
// 39-41 (AN-AP): Shop 1 Potion Prices
// 42-43 (AQ-AR): Shop 1 Primary, Price
// 44-45 (AS-AT): Shop 1 Secondary, Price
// 46-47 (AU-AV): Shop 1 Special, Price
// 48-49 (AW-AX): Shop 1 Defensive, Price
// 50-52 (AY-BA): Shop 2 Potions
// 53-55 (BB-BD): Shop 2 Potion Prices
// 56-57 (BE-BF): Shop 2 Primary, Price
// 58-59 (BG-BH): Shop 2 Secondary, Price
// 60-61 (BI-BJ): Shop 2 Special, Price
// 62-63 (BK-BL): Shop 2 Defensive, Price
// 64-66 (BM-BO): Shop 3 Potions
// 67-69 (BP-BR): Shop 3 Potion Prices
// 70-71 (BS-BT): Shop 3 Primary, Price
// 72-73 (BU-BV): Shop 3 Secondary, Price
// 74-75 (BW-BX): Shop 3 Special, Price
// 76-77 (BY-BZ): Shop 3 Defensive, Price
// 78-80 (CA-CC): Shop 4 Potions
// 81-83 (CD-CF): Shop 4 Potion Prices
// 84-85 (CG-CH): Shop 4 Primary, Price
// 86-87 (CI-CJ): Shop 4 Secondary, Price
// 88-89 (CK-CL): Shop 4 Special, Price
// 90-91 (CM-CN): Shop 4 Defensive, Price

// Commented out lines are not actual items but have IDs for reference
const itemObj = {
	// 0: 'nothing_item',
	// 1: '???',
	// 2: '???',
	// 3: '???',
	// 4: '???',
	// 5: '???',
	// 6: 'Dimi Moonburst',
	// 7: 'Diamond Dimi Moonburst',
	// 8: 'Opal Dimi Moonburst',
	// 9: 'Sapphire Dimi Moonburst',
	// 10: 'Ruby Dimi Moonburst',
	// 11: 'Garnet Dimi Moonburst',
	// 12: 'Emerald Dimi Moonburst',
	// 13: 'Lat Moonburst',
	// 14: 'Diamond Lat Moonburst',
	// 15: 'Opal Lat Moonburst',
	// 16: 'Sapphire Lat Moonburst',
	// 17: 'Ruby Lat Moonburst',
	// 18: 'Garnet Lat Moonburst',
	// 19: 'Emerald Lat Moonburst',
	// 20: 'Astral Swirl',
	// 21: 'Diamond Astral Swirl',
	// 22: 'Opal Astral Swirl',
	// 23: 'Sapphire Astral Swirl',
	// 24: 'Ruby Astral Swirl',
	// 25: 'Garnet Astral Swirl',
	// 26: 'Emerald Astral Swirl',
	// 27: 'Astral Seal',
	// 28: 'Diamond Astral Seal',
	// 29: 'Opal Astral Seal',
	// 30: 'Sapphire Astral Seal',
	// 31: 'Ruby Astral Seal',
	// 32: 'Garnet Astral Seal',
	// 33: 'Emerald Astral Seal',
	// 34: 'Swift Cut',
	// 35: 'Diamond Swift Cut',
	// 36: 'Opal Swift Cut',
	// 37: 'Sapphire Swift Cut',
	// 38: 'Ruby Swift Cut',
	// 39: 'Garnet Swift Cut',
	// 40: 'Emerald Swift Cut',
	// 41: 'Knife Juggle',
	// 42: 'Diamond Knife Juggle',
	// 43: 'Opal Knife Juggle',
	// 44: 'Sapphire Knife Juggle',
	// 45: 'Ruby Knife Juggle',
	// 46: 'Garnet Knife Juggle',
	// 47: 'Emerald Knife Juggle',
	// 48: 'Assassinate',
	// 49: 'Diamond Assassinate',
	// 50: 'Opal Assassinate',
	// 51: 'Sapphire Assassinate',
	// 52: 'Ruby Assassinate',
	// 53: 'Garnet Assassinate',
	// 54: 'Emerald Assassinate',
	// 55: 'Shadowstep',
	// 56: 'Diamond Shadowstep',
	// 57: 'Opal Shadowstep',
	// 58: 'Sapphire Shadowstep',
	// 59: 'Ruby Shadowstep',
	// 60: 'Garnet Shadowstep',
	// 61: 'Emerald Shadowstep',
	// 62: 'Full Moon',
	// 63: 'Diamond Full Moon',
	// 64: 'Opal Full Moon',
	// 65: 'Sapphire Full Moon',
	// 66: 'Ruby Full Moon',
	// 67: 'Garnet Full Moon',
	// 68: 'Emerald Full Moon',
	// 69: 'Dark Wave',
	// 70: 'Diamond Dark Wave',
	// 71: 'Opal Dark Wave',
	// 72: 'Sapphire Dark Wave',
	// 73: 'Ruby Dark Wave',
	// 74: 'Garnet Dark Wave',
	// 75: 'Emerald Dark Wave',
	// 76: 'Spinning Leap',
	// 77: 'Diamond Spinning Leap',
	// 78: 'Opal Spinning Leap',
	// 79: 'Sapphire Spinning Leap',
	// 80: 'Ruby Spinning Leap',
	// 81: 'Garnet Spinning Leap',
	// 82: 'Emerald Spinning Leap',
	// 83: 'Shadow Barrier',
	// 84: 'Diamond Shadow Barrier',
	// 85: 'Opal Shadow Barrier',
	// 86: 'Sapphire Shadow Barrier',
	// 87: 'Ruby Shadow Barrier',
	// 88: 'Garnet Shadow Barrier',
	// 89: 'Emerald Shadow Barrier',
	// 90: 'Twirling Rose',
	// 91: 'Diamond Twirling Rose',
	// 92: 'Opal Twirling Rose',
	// 93: 'Sapphire Twirling Rose',
	// 94: 'Ruby Twirling Rose',
	// 95: 'Garnet Twirling Rose',
	// 96: 'Emerald Twirling Rose',
	// 97: 'Falling Petal',
	// 98: 'Diamond Falling Petal',
	// 99: 'Opal Falling Petal',
	// 100: 'Sapphire Falling Petal',
	// 101: 'Ruby Falling Petal',
	// 102: 'Garnet Falling Petal',
	// 103: 'Emerald Falling Petal',
	// 104: 'Lily Blossom',
	// 105: 'Diamond Lily Blossom',
	// 106: 'Opal Lily Blossom',
	// 107: 'Sapphire Lily Blossom',
	// 108: 'Ruby Lily Blossom',
	// 109: 'Garnet Lily Blossom',
	// 110: 'Emerald Lily Blossom',
	// 111: 'Golden Grace',
	// 112: 'Diamond Golden Grace',
	// 113: 'Opal Golden Grace',
	// 114: 'Sapphire Golden Grace',
	// 115: 'Ruby Golden Grace',
	// 116: 'Garnet Golden Grace',
	// 117: 'Emerald Golden Grace',
	// 118: 'Dimi Life',
	// 119: 'Diamond Dimi Life',
	// 120: 'Opal Dimi Life',
	// 121: 'Sapphire Dimi Life',
	// 122: 'Ruby Dimi Life',
	// 123: 'Garnet Dimi Life',
	// 124: 'Emerald Dimi Life',
	// 125: 'Lat Life',
	// 126: 'Diamond Lat Life',
	// 127: 'Opal Lat Life',
	// 128: 'Sapphire Lat Life',
	// 129: 'Ruby Lat Life',
	// 130: 'Garnet Lat Life',
	// 131: 'Emerald Lat Life',
	// 132: 'Summon Spirit',
	// 133: 'Diamond Summon Spirit',
	// 134: 'Opal Summon Spirit',
	// 135: 'Sapphire Summon Spirit',
	// 136: 'Ruby Summon Spirit',
	// 137: 'Garnet Summon Spirit',
	// 138: 'Emerald Summon Spirit',
	// 139: "Nature's Blessing",
	// 140: "Diamond Nature's Blessing",
	// 141: "Opal Nature's Blessing",
	// 142: "Sapphire Nature's Blessing",
	// 143: "Ruby Nature's Blessing",
	// 144: "Garnet Nature's Blessing",
	// 145: "Emerald Nature's Blessing",
	// 146: 'Sword Thrust',
	// 147: 'Diamond Sword Thrust',
	// 148: 'Opal Sword Thrust',
	// 149: 'Sapphire Sword Thrust',
	// 150: 'Ruby Sword Thrust',
	// 151: 'Garnet Sword Thrust',
	// 152: 'Emerald Sword Thrust',
	// 153: 'Siphon Spell',
	// 154: 'Diamond Siphon Spell',
	// 155: 'Opal Siphon Spell',
	// 156: 'Sapphire Siphon Spell',
	// 157: 'Ruby Siphon Spell',
	// 158: 'Garnet Siphon Spell',
	// 159: 'Emerald Siphon Spell',
	// 160: 'Magicked Fleche',
	// 161: 'Diamond Magicked Fleche',
	// 162: 'Opal Magicked Fleche',
	// 163: 'Sapphire Magicked Fleche',
	// 164: 'Ruby Magicked Fleche',
	// 165: 'Garnet Magicked Fleche',
	// 166: 'Emerald Magicked Fleche',
	// 167: 'Novi Dark',
	// 168: 'Diamond Novi Dark',
	// 169: 'Opal Novi Dark',
	// 170: 'Sapphire Novi Dark',
	// 171: 'Ruby Novi Dark',
	// 172: 'Garnet Novi Dark',
	// 173: 'Emerald Novi Dark',
	// 174: 'Arrowshot',
	// 175: 'Diamond Arrowshot',
	// 176: 'Opal Arrowshot',
	// 177: 'Sapphire Arrowshot',
	// 178: 'Ruby Arrowshot',
	// 179: 'Garnet Arrowshot',
	// 180: 'Emerald Arrowshot',
	// 181: 'Rabbitsnare',
	// 182: 'Diamond Rabbitsnare',
	// 183: 'Opal Rabbitsnare',
	// 184: 'Sapphire Rabbitsnare',
	// 185: 'Ruby Rabbitsnare',
	// 186: 'Garnet Rabbitsnare',
	// 187: 'Emerald Rabbitsnare',
	// 188: 'Barrage',
	// 189: 'Diamond Barrage',
	// 190: 'Opal Barrage',
	// 191: 'Sapphire Barrage',
	// 192: 'Ruby Barrage',
	// 193: 'Garnet Barrage',
	// 194: 'Emerald Barrage',
	// 195: 'Careful Aim',
	// 196: 'Diamond Careful Aim',
	// 197: 'Opal Careful Aim',
	// 198: 'Sapphire Careful Aim',
	// 199: 'Ruby Careful Aim',
	// 200: 'Garnet Careful Aim',
	// 201: 'Emerald Careful Aim',
	// 202: 'Flame Hook',
	// 203: 'Diamond Flame Hook',
	// 204: 'Opal Flame Hook',
	// 205: 'Sapphire Flame Hook',
	// 206: 'Ruby Flame Hook',
	// 207: 'Garnet Flame Hook',
	// 208: 'Emerald Flame Hook',
	// 209: 'Quick Jab',
	// 210: 'Diamond Quick Jab',
	// 211: 'Opal Quick Jab',
	// 212: 'Sapphire Quick Jab',
	// 213: 'Ruby Quick Jab',
	// 214: 'Garnet Quick Jab',
	// 215: 'Emerald Quick Jab',
	// 216: 'Fury',
	// 217: 'Diamond Fury',
	// 218: 'Opal Fury',
	// 219: 'Sapphire Fury',
	// 220: 'Ruby Fury',
	// 221: 'Garnet Fury',
	// 222: 'Emerald Fury',
	// 223: 'Footwork',
	// 224: 'Diamond Footwork',
	// 225: 'Opal Footwork',
	// 226: 'Sapphire Footwork',
	// 227: 'Ruby Footwork',
	// 228: 'Garnet Footwork',
	// 229: 'Emerald Footwork',
	// 230: 'Spear Thrust',
	// 231: 'Diamond Spear Thrust',
	// 232: 'Opal Spear Thrust',
	// 233: 'Sapphire Spear Thrust',
	// 234: 'Ruby Spear Thrust',
	// 235: 'Garnet Spear Thrust',
	// 236: 'Emerald Spear Thrust',
	// 237: 'Lat Holy',
	// 238: 'Diamond Lat Holy',
	// 239: 'Opal Lat Holy',
	// 240: 'Sapphire Lat Holy',
	// 241: 'Ruby Lat Holy',
	// 242: 'Garnet Lat Holy',
	// 243: 'Emerald Lat Holy',
	// 244: 'Novi Holy',
	// 245: 'Diamond Novi Holy',
	// 246: 'Opal Novi Holy',
	// 247: 'Sapphire Novi Holy',
	// 248: 'Ruby Novi Holy',
	// 249: 'Garnet Novi Holy',
	// 250: 'Emerald Novi Holy',
	// 251: 'Roll & Phalanx',
	// 252: 'Diamond Roll & Phalanx',
	// 253: 'Opal Roll & Phalanx',
	// 254: 'Sapphire Roll & Phalanx',
	// 255: 'Ruby Roll & Phalanx',
	// 256: 'Garnet Roll & Phalanx',
	// 257: 'Emerald Roll & Phalanx',
	// 258: 'Strike Command',
	// 259: 'Diamond Strike Command',
	// 260: 'Opal Strike Command',
	// 261: 'Sapphire Strike Command',
	// 262: 'Ruby Strike Command',
	// 263: 'Garnet Strike Command',
	// 264: 'Emerald Strike Command',
	// 265: 'March Command',
	// 266: 'Diamond March Command',
	// 267: 'Opal March Command',
	// 268: 'Sapphire March Command',
	// 269: 'Ruby March Command',
	// 270: 'Garnet March Command',
	// 271: 'Emerald March Command',
	// 272: 'Abyssal Call',
	// 273: 'Diamond Abyssal Call',
	// 274: 'Opal Abyssal Call',
	// 275: 'Sapphire Abyssal Call',
	// 276: 'Ruby Abyssal Call',
	// 277: 'Garnet Abyssal Call',
	// 278: 'Emerald Abyssal Call',
	// 279: 'Protect Command',
	// 280: 'Diamond Protect Command',
	// 281: 'Opal Protect Command',
	// 282: 'Sapphire Protect Command',
	// 283: 'Ruby Protect Command',
	// 284: 'Garnet Protect Command',
	// 285: 'Emerald Protect Command',
	// 286: '???',
	287: 'Raven Grimoire',
	288: 'Blackwing Staff',
	289: 'Curse Talon',
	290: 'Darkmagic Blade',
	291: "Witch's Cloak",
	292: 'Crowfeather Hairpin',
	293: 'Redblack Ribbon',
	294: 'Opal Necklace',
	295: 'Sleeping Greatbow',
	296: 'Crescentmoon Dagger',
	297: 'Lullaby Harp',
	298: 'Nightstar Grimoire',
	299: 'Moon Pendant',
	300: 'Pajama Hat',
	301: 'Stuffed Rabbit',
	302: 'Nightingale Gown',
	303: 'Eternity Flute',
	304: 'Timewarp Wand',
	305: 'Chrome Shield',
	306: 'Clockwork Tome',
	307: 'Metronome Boots',
	308: 'Timemage Cap',
	309: 'Starry Cloak',
	310: 'Gemini Necklace',
	311: 'Hawkfeather Fan',
	312: 'Windbite Dagger',
	313: 'Pidgeon Bow',
	314: 'Shinsoku Katana',
	315: 'Eaglewing Charm',
	316: 'Sparrow Feather',
	317: 'Winged Cap',
	318: "Thief's Coat",
	319: 'Vampiric Dagger',
	320: 'Bloody Bandage',
	321: 'Leech Staff',
	322: 'Bloodhound Greatsword',
	323: 'Reaper Cloak',
	324: 'Bloodflower Brooch',
	325: 'Wolf Hood',
	326: 'Blood Vial',
	327: 'Black Wakizashi',
	328: 'Throwing Dagger',
	329: "Assassin's Knife",
	330: 'Ninjutsu Scroll',
	331: 'Shadow Bracelet',
	332: 'Ninja Robe',
	333: 'Kunoichi Hood',
	334: 'Shinobi Tabi',
	335: 'Dragonhead Spear',
	336: 'Granite Greatsword',
	337: 'Greysteel Shield',
	338: 'Stonebreaker Staff',
	339: 'Tough Gauntlet',
	340: 'Rockdragon Mail',
	341: 'Obsidian Hairpin',
	342: 'Iron Greaves',
	343: 'Volcano Spear',
	344: 'Reddragon Blade',
	345: 'Flame Bow',
	346: 'Meteor Staff',
	347: 'Phoenix Charm',
	348: 'Firescale Corset',
	349: 'Demon Horns',
	350: 'Flamewalker Boots',
	351: 'Diamond Shield',
	352: 'Peridot Rapier',
	353: 'Garnet Staff',
	354: 'Sapphire Violin',
	355: 'Emerald Chestplate',
	356: 'Amethyst Bracelet',
	357: 'Topaz Charm',
	358: 'Ruby Circlet',
	359: 'Brightstorm Spear',
	360: 'Bolt Staff',
	361: 'Lightning Bow',
	362: 'Darkstorm Knife',
	363: 'Darkcloud Necklace',
	364: 'Crown of Storms',
	365: 'Thunderclap Gloves',
	366: 'Storm Petticoat',
	367: 'Holy Greatsword',
	368: 'Sacred Bow',
	369: 'Purification Rod',
	370: 'Ornamental Bell',
	371: "Shrinemaiden's Kosode",
	372: 'Redwhite Ribbon',
	373: 'Divine Mirror',
	374: 'Golden Chime',
	375: 'Book of Cheats',
	376: 'Golden Katana',
	377: 'Glittering Trumpet',
	378: 'Royal Staff',
	379: 'Ballroom Gown',
	380: 'Silver Coin',
	381: "Queen's Crown",
	382: 'Mimick Rabbitfoot',
	383: 'Butterfly Ocarina',
	384: 'Fairy Spear',
	385: 'Moss Shield',
	386: 'Floral Bow',
	387: 'Blue Rose',
	388: 'Sunflower Crown',
	389: 'Midsummer Dress',
	390: 'Grasswoven Bracelet',
	391: 'Snakefang Dagger',
	392: 'Ivy Staff',
	393: 'Deathcap Tome',
	394: 'Spiderbite Bow',
	395: 'Compound Gloves',
	396: 'Poisonfrog Charm',
	397: 'Venom Hood',
	398: "Chemist's Coat",
	399: 'Seashell Shield',
	400: 'Necronomicon',
	401: 'Tidal Greatsword',
	402: 'Occult Dagger',
	403: 'Mermaid Scalemail',
	404: 'Hydrous Blob',
	405: 'Abyss Artifact',
	406: 'Lost Pendant',
	407: 'Sawtooth Cleaver',
	408: "Raven's Dagger",
	409: 'Killing Note',
	410: 'Blacksteel Buckler',
	411: 'Nightguard Gloves',
	412: "Sniper's Eyeglasses",
	413: 'Darkmage Charm',
	414: 'Firststrike Bracelet',
	415: 'Obsidian Rod',
	416: 'Darkglass Spear',
	417: 'Timespace Dagger',
	418: 'Quartz Shield',
	419: 'Pocketwatch',
	420: 'Nova Crown',
	421: 'Blackhole Charm',
	422: 'Twinstar Earrings',
	423: 'Kyou No Omikuji',
	424: 'Youkai Bracelet',
	425: 'Oni Staff',
	426: 'Kappa Shield',
	427: 'Usagi Kamen',
	428: 'Red Tanzaku',
	429: 'Vega Spear',
	430: 'Altair Dagger',
	431: 'Ghost Spear',
	432: 'Phantom Dagger',
	433: 'Cursed Candlestaff',
	434: 'Haunted Gloves',
	435: 'Old Bonnet',
	436: 'Maid Outfit',
	437: 'Calling Bell',
	438: 'Smoke Shield',
	439: 'Grandmaster Spear',
	440: 'Teacher Knife',
	441: 'Tactician Rod',
	442: 'Spiked Shield',
	443: 'Battlemaiden Armor',
	444: 'Gladiator Helmet',
	445: 'Lancer Gauntlets',
	446: 'Lion Charm',
	447: 'Bluebolt Staff',
	448: 'Lapis Sword',
	449: 'Shockwave Tome',
	450: 'Battery Shield',
	451: 'Raiju Crown',
	452: 'Staticshock Earrings',
	453: 'Stormdance Gown',
	454: 'Blackbolt Ribbon',
	455: 'Crane Katana',
	456: 'Falconfeather Dagger',
	457: 'Tornado Staff',
	458: 'Cloud Guard',
	459: 'Hermes Bow',
	460: 'Talon Charm',
	461: 'Tiny Wings',
	462: 'Feathered Overcoat',
	463: 'Sandpriestess Spear',
	464: 'Flamedancer Dagger',
	465: 'Whiteflame Staff',
	466: 'Sacred Shield',
	467: 'Marble Clasp',
	468: 'Sun Pendant',
	469: 'Tiny Hourglass',
	470: 'Desert Earrings',
	471: 'Giant Stone Club',
	472: 'Ruins Sword',
	473: 'Mountain Staff',
	474: 'Boulder Shield',
	475: "Golem's Claymore",
	476: 'Stoneplate Armor',
	477: 'Sacredstone Charm',
	478: 'Clay Rabbit',
	479: 'Waterfall Polearm',
	480: 'Vorpal Dao',
	481: 'Jade Staff',
	482: 'Reflection Shield',
	483: 'Butterfly Hairpin',
	484: 'Watermage Pendant',
	485: 'Raindrop Earrings',
	486: 'Aquamarine Bracelet',
	// 487: 'Full Heal',
	// 488: 'Level Up',
	489: 'Regeneration Potion',
	490: 'Essence of Spell',
	491: 'Darkness Potion',
	492: 'Quickening Potion',
	493: 'Winged Potion',
	494: 'Essence of Wit',
	495: 'Swifthand Potion',
	496: 'Fire Potion',
	497: 'Essence of Strength',
	498: 'Golden Potion',
	499: 'Luck Potion',
	500: 'Essence of Steel',
	501: 'Evasion Potion',
	502: 'Longarm Potion',
	503: 'Vitality Potion',
	504: 'Opal Primary Upgrade',
	505: 'Opal Secondary Upgrade',
	506: 'Opal Special Upgrade',
	507: 'Opal Defensive Upgrade',
	508: 'Sapphire Primary Upgrade',
	509: 'Sapphire Secondary Upgrade',
	510: 'Sapphire Special Upgrade',
	511: 'Sapphire Defensive Upgrade',
	512: 'Ruby Primary Upgrade',
	513: 'Ruby Secondary Upgrade',
	514: 'Ruby Special Upgrade',
	515: 'Ruby Defensive Upgrade',
	516: 'Garnet Primary Upgrade',
	517: 'Garnet Secondary Upgrade',
	518: 'Garnet Special Upgrade',
	519: 'Garnet Defensive Upgrade',
	520: 'Emerald Primary Upgrade',
	521: 'Emerald Secondary Upgrade',
	522: 'Emerald Special Upgrade',
	523: 'Emerald Defensive Upgrade'
};

const idItemMap = new Map(Object.entries(itemObj));
const itemIdMap = new Map(Object.entries(itemObj).map(([id, item]) => [item, id]));

export const itemList = Object.values(itemObj);

export function name_to_id(name: string): number {
	return Number(itemIdMap.get(name) ?? 0);
}

export function id_to_name(id: number): string {
	return idItemMap.get(String(id)) ?? 'ERROR_ITEM';
}

// skill_index referring to the skill (primary, secondary, special, defensive), starting at 0
export function gem_to_id(gem: string, skill_index: number): number | undefined {
	let gem_index: number;
	switch (gem) {
		case 'Opal':
			gem_index = 0;
			break;
		case 'Sapphire':
			gem_index = 1;
			break;
		case 'Ruby':
			gem_index = 2;
			break;
		case 'Garnet':
			gem_index = 3;
			break;
		case 'Emerald':
			gem_index = 4;
			break;
		default:
			return undefined;
	}
	return 504 + gem_index * 4 + skill_index;
}
